### ISSUE TITLE
Putting Chinese in the code will finally get garbled text after running on the WebGPU

### ISSUE THREAD

**Issue by XimingCheng** [abduld/libwb#25]
The code cu template skel text files are all encoded with ANSI, not UTF-8.
When I wrote some comments in Chinese in the cu files, after running on the WebGPU, I got this
![capture](https://cloud.githubusercontent.com/assets/2611722/6130398/cc041e90-b17f-11e4-85e9-a1c140f3acae.PNG)

Please fix this, thanks

**Comment by abduld** [comment]
removed skel
