### ISSUE TITLE
libwb JSON viewer (wbLogger)

### ISSUE THREAD

**Issue by csullivan** [abduld/libwb#34]
Is there an available JSON parser (javascript) similar to the WebGPU site that can be used to view the output of the wbLogger? I am able to compile and run the WebGPU labs without difficulty, but reading JSON in the terminal from the logger is not pleasant. 

Many thanks!

**Comment by abduld** [comment]
You can use any online json viewer http://codebeautify.org/jsonviewer. There is no viewer developed aside from the one in webgpu. I can accept pull requests however.
